#ifndef OPENVXWRAPPER_GLOBAL_H
#define OPENVXWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OPENVXWRAPPER_LIB
# define OPENVXWRAPPER_EXPORT Q_DECL_EXPORT
#else
# define OPENVXWRAPPER_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENVXWRAPPER_GLOBAL_H
